sonar.projectKey=leapmentor-backend
sonar.projectName=LeapMentor Backend
sonar.host.url=http://localhost:9000
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/swagger-output.json,**/swagger-autogen.js,**/swagger.js,**/coverage/**,**/*.html
sonar.cpd.exclusions=**/coverage/**,**/*.test.js,**/*.spec.js,**/*.html
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/node_modules/**